---
- name: generate wireguard subnets
  script: generate_subnets.py
  register: python_result
  environment:
    ANSIBLE_WIREGUARD_PEERS: "{{ wireguard.peers | to_json }}"

- name: set generates subnets fact
  set_fact:
    subnets: "{{ python_result.stdout | from_json }}"
