---
- name: generate wireguard subnets
  script: generate_subnets.py --peers '{{ wireguard.peers | to_json }}'
  register: subnets_result

- name: set generates subnets fact
  set_fact:
    subnets: "{{ subnets_result.stdout | from_json }}"
