---
- name: install wireguard
  ansible.builtin.apt:
    name:
      - wireguard
    state: latest
    update_cache: yes

- name: copy wireguard config
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0644
  notify:
    - restart wireguard

- name: enable and start wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg0.service
    enabled: yes
    state: started

# flush handlers to start triggered handlers before next task is executed
- meta: flush_handlers
