---
- name: install requirements
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - python3-pip
    state: latest
    update_cache: yes

- name: add docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    mode: '0666'

- name: install docker engine
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: install docker pip module
  become: yes
  pip:
    name: docker
